display_manager:
  is_display: true    # 是否启用本机的 GUI 交互窗口

yolo:
  yolo_engine: "/home/work/Stereo-Detection/model/engine/yolov8s_s640_ws1024_fp16.engine"
  yolo_nms_thresh: 0.4    # YOLO NMS阈值 (下采样截断遮挡框)
  yolo_conf_thresh: 0.25

depth:
  depth_interval: 1       # 隔帧推理深度间隔，优化算力占用
  depth_engine: "/home/work/Stereo-Detection/model/engine/lite_mono-8m_op12_s640_ws-all_fp16.engine"

motion_state_engine:      # 目标追踪与状态转换引擎
  velocity_threshold: 20      # 判断趋近/远离的速度触发线
  acceleration_threshold: 10   # 加减速缓冲界限
  kf_process_noise_cov: 0.02  # 卡尔曼过程噪声
  kf_measurement_noise_cov: 0.05

io_manager:
  out_dir: "out_dir"      # 落盘文件夹名称
  save_mode: video        # 保存输出: video / images / both / none